import { Order } from "./types";

export const mockOrders: Order[] = [
  {
    id: "ord-9281",
    tracking_id: "TMK-9281",
    customer_name: "Elena Vance",
    customer_email: "elena@example.com",
    customer_phone: "+44 7700 900111",
    shipping_address: {
      fullName: "Elena Vance",
      email: "elena@example.com",
      phone: "+44 7700 900111",
      street: "12 King Street",
      city: "London",
      state: "Greater London",
      postalCode: "SW1A 1AA",
      country: "United Kingdom",
    },
    status: "processing",
    currency: "GBP",
    payment_gateway: "stripe",
    payment_reference: "pi_3QTMK9281",
    items: [
      {
        product_id: "prod-001",
        product_name: "Full Body Shaper Bra",
        quantity: 1,
        size: "M",
        color: "Nude",
        unit_price: 89.99,
        subtotal: 89.99,
      },
    ],
    subtotal: 89.99,
    shipping_cost: 8,
    tax: 0,
    discount_applied: 0,
    total_amount: 97.99,
    created_at: new Date("2026-07-19T09:24:00"),
    updated_at: new Date("2026-07-19T09:24:00"),
  },
  {
    id: "ord-9275",
    tracking_id: "TMK-9275",
    customer_name: "Marcus Thorne",
    customer_email: "marcus@example.com",
    customer_phone: "+44 7700 900222",
    shipping_address: {
      fullName: "Marcus Thorne",
      email: "marcus@example.com",
      phone: "+44 7700 900222",
      street: "88 Camden Road",
      city: "Manchester",
      state: "Greater Manchester",
      postalCode: "M1 4BT",
      country: "United Kingdom",
    },
    status: "shipped",
    currency: "GBP",
    payment_gateway: "paystack",
    payment_reference: "ps_4TMK9275",
    items: [
      {
        product_id: "prod-002",
        product_name: "Waist Trainer Pro",
        quantity: 1,
        size: "L",
        color: "Black",
        unit_price: 65,
        subtotal: 65,
      },
    ],
    subtotal: 65,
    shipping_cost: 6.5,
    tax: 0,
    discount_applied: 0,
    total_amount: 71.5,
    created_at: new Date("2026-07-19T08:11:00"),
    updated_at: new Date("2026-07-19T10:02:00"),
  },
  {
    id: "ord-9269",
    tracking_id: "TMK-9269",
    customer_name: "Lila Rosier",
    customer_email: "lila@example.com",
    customer_phone: "+44 7700 900333",
    shipping_address: {
      fullName: "Lila Rosier",
      email: "lila@example.com",
      phone: "+44 7700 900333",
      street: "44 Portland Place",
      city: "Birmingham",
      state: "West Midlands",
      postalCode: "B1 2JT",
      country: "United Kingdom",
    },
    status: "delivered",
    currency: "GBP",
    payment_gateway: "stripe",
    payment_reference: "pi_3QTMK9269",
    items: [
      {
        product_id: "prod-003",
        product_name: "Seamless Bodysuit",
        quantity: 2,
        size: "S",
        color: "Nude",
        unit_price: 54.99,
        subtotal: 109.98,
      },
    ],
    subtotal: 109.98,
    shipping_cost: 0,
    tax: 0,
    discount_applied: 10,
    total_amount: 99.98,
    created_at: new Date("2026-07-18T16:45:00"),
    updated_at: new Date("2026-07-19T08:30:00"),
  },
  {
    id: "ord-9260",
    tracking_id: "TMK-9260",
    customer_name: "Sarah Monroe",
    customer_email: "sarah@example.com",
    customer_phone: "+44 7700 900444",
    shipping_address: {
      fullName: "Sarah Monroe",
      email: "sarah@example.com",
      phone: "+44 7700 900444",
      street: "7 Queen Victoria St",
      city: "Leeds",
      state: "West Yorkshire",
      postalCode: "LS1 2HE",
      country: "United Kingdom",
    },
    status: "out-for-delivery",
    currency: "GBP",
    payment_gateway: "stripe",
    payment_reference: "pi_3QTMK9260",
    items: [
      {
        product_id: "prod-004",
        product_name: "Sculpting Tank Top",
        quantity: 1,
        size: "M",
        color: "Black",
        unit_price: 45,
        subtotal: 45,
      },
    ],
    subtotal: 45,
    shipping_cost: 5,
    tax: 0,
    discount_applied: 0,
    total_amount: 50,
    created_at: new Date("2026-07-18T14:20:00"),
    updated_at: new Date("2026-07-19T11:18:00"),
  },
];
