import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    name: "Full Body Shaper Bra",
    description: "Ultimate shaping coverage from bust to hip",
    longDescription:
      "Experience ultimate confidence with our Full Body Shaper Bra. Engineered with premium compression fabric, this bra provides seamless shaping from bust to hips. The integrated support system offers superior lift and defines your silhouette beautifully. Perfect for any occasion.",
    price_gbp: 89.99,
    price_ngn: 45000,
    price_usd: 110.0,
    category: "shapewear",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#000000", inventory: 50 },
      { name: "Nude", hex: "#E8C9A0", inventory: 45 },
      { name: "White", hex: "#FFFFFF", inventory: 40 },
    ],
    stock_qty: 135,
    low_stock_threshold: 20,
    sku: "FUSE-001",
    images: ["/shop-img/imgi_10_fb_shp.png", "/shop-img/imgi_8_shaper.png"],
    featured: true,
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    id: "prod-002",
    name: "Waist Trainer Pro",
    description: "Professional-grade waist cinching and support",
    longDescription:
      "The Waist Trainer Pro features 3-layer compression technology with steel boning for optimal support. Adjustable straps ensure a perfect fit, and the breathable mesh lining keeps you comfortable throughout the day. Ideal for workouts, posture correction, and everyday wear.",
    price_gbp: 65.0,
    price_ngn: 32500,
    price_usd: 79.99,
    category: "waist-trainer",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000", inventory: 60 },
      { name: "Nude", hex: "#E8C9A0", inventory: 55 },
    ],
    stock_qty: 115,
    low_stock_threshold: 20,
    sku: "WT-PRO-001",
    images: [
      "/shop-img/imgi_13_waist_wrp.png",
      "/shop-img/imgi_24_img_8677-1.jpg",
    ],
    featured: true,
    created_at: new Date("2024-01-10"),
    updated_at: new Date("2024-01-10"),
  },
  {
    id: "prod-003",
    name: "Seamless Bodysuit",
    description: "Invisible under any outfit",
    longDescription:
      "Our Seamless Bodysuit combines comfort with invisible support. Made from ultra-smooth nylon/spandex blend, it creates a seamless silhouette under your clothing. The open gusset provides convenience, and the breathable fabric keeps you fresh all day.",
    price_gbp: 54.99,
    price_ngn: 27500,
    price_usd: 67.0,
    category: "shapewear",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#000000", inventory: 75 },
      { name: "Nude", hex: "#E8C9A0", inventory: 70 },
      { name: "Tan", hex: "#D4A574", inventory: 65 },
    ],
    stock_qty: 210,
    low_stock_threshold: 30,
    sku: "SB-001",
    images: [
      "/shop-img/imgi_14_nu_bella.png",
      "/shop-img/imgi_16_nu_amanda.png",
    ],
    featured: true,
    created_at: new Date("2024-01-05"),
    updated_at: new Date("2024-01-05"),
  },
  {
    id: "prod-004",
    name: "Sculpting Tank Top",
    description: "Targeted upper body shaping",
    longDescription:
      "The Sculpting Tank Top provides targeted compression for the chest, back, and sides. The reinforced support gives you the confidence you need while maintaining a natural look under clothing. Layer it or wear it alone for versatile styling options.",
    price_gbp: 45.0,
    price_ngn: 22500,
    price_usd: 55.0,
    category: "shapewear",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000", inventory: 40 },
      { name: "Nude", hex: "#E8C9A0", inventory: 35 },
    ],
    stock_qty: 75,
    low_stock_threshold: 15,
    sku: "ST-001",
    images: [
      "/shop-img/imgi_16_nu_amanda.png",
      "/shop-img/imgi_96_img_2830.jpg",
    ],
    featured: false,
    created_at: new Date("2024-01-08"),
    updated_at: new Date("2024-01-08"),
  },
  {
    id: "prod-005",
    name: "Thigh Slimmer Shorts",
    description: "Smooth lines from waist to knee",
    longDescription:
      "Get smooth, sculpted lines with our Thigh Slimmer Shorts. The mid-thigh length provides optimal coverage while the compression fabric reduces visible panty lines and smooths your silhouette. Breathable and comfortable for all-day wear.",
    price_gbp: 39.99,
    price_ngn: 20000,
    price_usd: 49.0,
    category: "shapewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000", inventory: 50 },
      { name: "Nude", hex: "#E8C9A0", inventory: 48 },
    ],
    stock_qty: 98,
    low_stock_threshold: 20,
    sku: "TSS-001",
    images: [
      "/shop-img/imgi_9_2-5.jpg",
      "/shop-img/imgi_81_img_7941-1536x1536.jpg",
    ],
    featured: false,
    created_at: new Date("2024-01-12"),
    updated_at: new Date("2024-01-12"),
  },
  {
    id: "prod-006",
    name: "High-Waist Control Shorts",
    description: "Maximum tummy control and definition",
    longDescription:
      "Our High-Waist Control Shorts feature a reinforced waistband that smooths and shapes while the side panels provide targeted compression. The durable, flexible fabric adapts to your body for all-day comfort without rolling or riding up.",
    price_gbp: 49.99,
    price_ngn: 25000,
    price_usd: 61.0,
    category: "shapewear",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#000000", inventory: 60 },
      { name: "Nude", hex: "#E8C9A0", inventory: 55 },
      { name: "Caramel", hex: "#C9956F", inventory: 50 },
    ],
    stock_qty: 165,
    low_stock_threshold: 25,
    sku: "HWCS-001",
    images: [
      "/shop-img/imgi_96_img_2830.jpg",
      "/shop-img/imgi_85_img_7941.jpg",
    ],
    featured: false,
    created_at: new Date("2024-01-09"),
    updated_at: new Date("2024-01-09"),
  },
];
